export const PRODUCT_LIST_REQUEST="PRODUCT_LIST_REQUEST"
export const PRODUCT_LIST_SUCCESS="PRODUCT_LIST_SUCCESS"
export const PRODUCT_LIST_FAIL="PRODUCT_LIST_FAIL"


export const PRODUCT_DETAIL_REQUEST="PRODUCT_DETAIL_REQUEST"
export const PRODUCT_DETAIL_SUCCESS="PRODUCT_DETAIL_SUCCESS"
export const PRODUCT_DETAIL_FAIL="PRODUCT_DETAIL_FAIL"

export const ADD_ITEM = "ADD_ITEM"
export const REMOVE_ITEM ="REMOVE_ITEM"


export const SAVE_SHIPPING_ADDRESS="SAVE_SHIPPING_ADDRESS"
export const payment_Shipping_Address="payment_Shipping_Address"